baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Aayush Chadha'
theme = 'typo'

[taxonomies]
tag = 'tags'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[params]
# Meta description
description = "Aayush Chadha | Portfolio"

# Appearance settings
theme = 'light'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hi! 👋🏼'
homeIntroContent = """
I am an engineer who works across the atoms to bits stack. I did my PhD in Nanosciences at the University of Manchester, where I built nanomaterials based
photodetectors, wireless power transfer systems and designed some really tiny circuit boards. Before that, I worked as a data engineer and did an undergraduate
degree in Artificial Intelligence. Currently exploring neurotechnology and quantum computing.
"""

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "linkedin"
url = "www.linkedin.com/in/aayush-chadha"

[[params.social]]
name = "github"
url = "https://github.com/achadha0111"

[[params.social]]
name = "x"
url = "https://x.com/AayushChad40496"

[[params.social]]
name = "devpost"
url = "https://devpost.com/achadha0111?ref_content=user-portfolio&ref_feature=portfolio&ref_medium=global-nav"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "about"
url = "/about"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"
